### PR TITLE
Do a local merge for open PR test

### LINKED ISSUE #43: open PR test should do a merge
open PR test should do a merge

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #43 : Do a local merge for open PR test

Review @smarter

### CODE REVIEW

**Comment by smarter** [comment]
If the merge fails, what happens?

**Comment by smarter** [comment]
Alternatively you can use the github automatically-generated merged branch for the PR:
```scala
git fetch origin +refs/pull/XXXX/merge:
```
where `XXXX` is the number of the PR.

**Comment by liufengyun** [comment]
If the merge fails, we'll receive a failure message from the bot.

**Review by smarter — APPROVED** [review]

**Comment by smarter** [comment]
It might be good if the message posted by the bot with the URL of the benchmarks for the PR said "benchmarks for this PR merged with commit xxxx from master"

**Comment by liufengyun** [comment]
Thanks @smarter , the message is now updated.

**Comment by liufengyun** [comment]
test performance please 4013bb8 4f25208

**Pull request merged**
