### PR TITLE
Fix benchmarks

### PR DESCRIPTION
**Pull request by nicolasstucki**
There where some bugs that we missed in the code which made some of the benchmarks fail

### CODE REVIEW

**Review by liufengyun — APPROVED** [review]
LGTM, thanks

**Comment by nicolasstucki** [comment]
@liufengyun are these changes on the benchmark machine yet?

**Comment by liufengyun** [comment]
Yes, they are. However, there is a bug, which was just fixed in https://github.com/liufengyun/bench/commit/6e0338fd3ae513427c3abe020601502bcdd0651e.

**Comment by nicolasstucki** [comment]
Perfect

**Comment by nicolasstucki** [comment]
Thanks

**Pull request merged**
