### PR TITLE
Add scalap: second attempt

### PR DESCRIPTION
**Pull request by allanrenucci**

### CODE REVIEW

**Comment by liufengyun** [comment]
Nice, it works 👍 We also need to restore the removal in `bin/charts.js`.

**Comment by liufengyun** [comment]
There is a minor issue with the CI for scripts:

```
/home/travis/build/liufengyun/bench/bin/common: line 32: datamash: command not found
bin/gauge: line 47: ghi: command not found
bin/gauge: line 47: ghi: command not found
```

I can take care of the issue later.

**Comment by allanrenucci** [comment]
Merging. We can fix the CI script later. Can you retroactively run the benchmarks?

**Comment by liufengyun** [comment]
Sure, I'll do that.

**Comment by liufengyun** [comment]
Deployed and regressional benchmarks scheduled (for two month, every 5 merges), total 27 points.

**Pull request merged**
